"""
Answer Generation Module

Maps to SKILL.md: Step 4 — Organize Information and Respond.

Answer structure per SKILL.md special requirements:
  1. Conclusion first — top 1–3 recommended courses
  2. Reasons — 1–3 sentences per recommendation
  3. Risk warnings — conflicts, unmet prereqs, workload
  4. Alternatives — if top picks have issues
  5. Follow-up questions — generated by followup.py

Style requirements:
  - Natural, direct, practical
  - Sound like a knowledgeable advisor, not a database echo
  - Convert raw fields into human-readable judgments
  - If info is incomplete, state what the advice is based on
  - If no results, suggest loosening constraints

TODO: Replace template-based generation with LLM-based generation
      via llm/adapter.py → generate_answer_llm()
"""

from typing import Optional


def generate_recommendation_answer(query_results: dict, session_state: dict) -> str:
    """
    Generate a structured recommendation response from query results.
    """
    primary = query_results.get("primary", [])
    flagged = query_results.get("flagged", [])
    total = query_results.get("total_found", 0)

    if not primary and not flagged:
        return _empty_results_response(session_state)

    parts = []

    # ── 1. Conclusion ─────────────────────────────────────
    top = primary[:3]
    if top:
        parts.append("**Here's what I'd recommend:**\n")
        for i, item in enumerate(top, 1):
            c = item["course"]
            best_section = _best_section(item["sections"])
            parts.append(f"**{i}. {c['course_id']} — {c['title']}** ({c['units']} units)")

            # ── 2. Reasons ────────────────────────────────
            reasons = _build_reasons(item, best_section, session_state)
            parts.append(reasons)
            parts.append("")  # blank line

    # ── 3. Risk Warnings ──────────────────────────────────
    warnings = _build_warnings(primary + flagged)
    if warnings:
        parts.append("**⚠️ Heads up:**")
        parts.append(warnings)
        parts.append("")

    # ── 4. Alternatives ───────────────────────────────────
    if flagged:
        parts.append("**Backup options** (have some caveats):")
        for item in flagged[:2]:
            c = item["course"]
            caveat = ""
            if not item["prereq_met"]:
                caveat = f" — missing prereqs: {', '.join(item['prereq_missing'])}"
            if item["has_conflict"]:
                caveat += " — has a time conflict"
            parts.append(f"- {c['course_id']} — {c['title']}{caveat}")
        parts.append("")

    return "\n".join(parts)


def generate_single_query_answer(course_data: dict) -> str:
    """Generate a concise answer for a single-point query."""
    if not course_data:
        return "I couldn't find that course in my records. Could you double-check the course ID?"

    c = course_data["course"]
    parts = [f"**{c['course_id']} — {c['title']}** ({c['units']} units)\n"]
    parts.append(c.get("description", ""))

    # Prerequisites
    prereqs = course_data.get("prerequisites", [])
    if prereqs:
        parts.append(f"\n**Prerequisites:** {', '.join(prereqs)}")
    else:
        parts.append("\n**Prerequisites:** None")

    # GE / Major
    if c.get("ge_category"):
        parts.append(f"**GE Category:** {c['ge_category']}")
    if c.get("major_requirement"):
        parts.append(f"**Counts toward:** {', '.join(c['major_requirement'])}")

    # Grade distribution
    grades = course_data.get("grade_distribution")
    if grades:
        parts.append(f"\n**Grade distribution:** avg GPA {grades['avg_gpa']:.1f} "
                      f"({grades['pct_A']}% A, {grades['pct_B']}% B, "
                      f"{grades['pct_C']}% C)")

    # Sections
    sections = course_data.get("sections", [])
    if sections:
        parts.append(f"\n**Available sections:**")
        for sec in sections:
            prof = sec.get("professor_rating") or {}
            rating_str = f" — RMP {prof['overall']}/5" if prof.get("overall") else ""
            seats = sec.get("seats_open", "?")
            parts.append(
                f"- Sec {sec['section']}: {sec['instructor']}{rating_str} | "
                f"{sec['days']} {sec['time']} | {seats} seats open"
            )

    return "\n".join(parts)


def generate_professor_answer(name: str, rating: Optional[dict]) -> str:
    """Generate a concise professor rating summary."""
    if not rating or not rating.get("overall"):
        return f"I don't have rating data for {name}."

    r = rating
    tags = ", ".join(r.get("top_tags", [])[:3])
    return (
        f"**{name}**\n"
        f"- Overall: {r['overall']}/5.0\n"
        f"- Difficulty: {r['difficulty']}/5.0\n"
        f"- Would take again: {r['would_take_again']}%\n"
        f"- Students say: {tags}"
    )


def generate_off_topic_response(message: str) -> str:
    """Friendly response for non-course-related questions."""
    return (
        "I'm your UCI course advisor, so I'm best at helping with course selection, "
        "professor recommendations, schedule planning, and prerequisite checks. "
        "Feel free to ask me anything about your upcoming courses!"
    )


# ── Internal helpers ─────────────────────────────────────

def _best_section(sections: list[dict]) -> Optional[dict]:
    """Pick the section with the best professor rating."""
    best = None
    best_score = -1
    for sec in sections:
        pr = sec.get("professor_rating") or {}
        score = pr.get("overall") or 0
        if score > best_score:
            best_score = score
            best = sec
    return best


def _build_reasons(item: dict, section: Optional[dict], state: dict) -> str:
    """Build 1–3 sentence reason string."""
    reasons = []
    c = item["course"]
    grades = item.get("grade_distribution") or {}

    # Major match
    major = state.get("major")
    if major and major in c.get("major_requirement", []):
        reasons.append(f"Counts toward your {major} requirements.")

    # Grade ease
    avg_gpa = grades.get("avg_gpa", 0)
    if avg_gpa >= 3.3:
        reasons.append(f"Historically generous grading (avg GPA {avg_gpa:.1f}).")
    elif avg_gpa <= 2.7:
        reasons.append(f"Tends to be tough grading-wise (avg GPA {avg_gpa:.1f}).")

    # Professor
    if section:
        pr = section.get("professor_rating") or {}
        if pr.get("overall") and pr["overall"] >= 4.5:
            reasons.append(f"{section['instructor']} is highly rated ({pr['overall']}/5).")

    return " ".join(reasons) if reasons else "Solid option based on available data."


def _build_warnings(all_items: list[dict]) -> str:
    """Aggregate warnings from all candidate items."""
    warnings = []
    for item in all_items:
        cid = item["course"]["course_id"]
        if not item["prereq_met"]:
            warnings.append(f"- {cid} requires {', '.join(item['prereq_missing'])} which you haven't completed yet.")
        if item["has_conflict"]:
            warnings.append(f"- {cid} has a time conflict with your current schedule.")
    return "\n".join(warnings)


def _empty_results_response(state: dict) -> str:
    """
    Maps to SKILL.md: 'Result Empty Handling.'
    Never just say 'no results.' Suggest loosening constraints.
    """
    suggestions = []
    if state.get("preferred_time"):
        suggestions.append("- Try widening your preferred time window")
    if state.get("difficulty_preference") == "easy":
        suggestions.append("- Consider including moderate-difficulty courses")
    if state.get("recommendation_goal") == "major_requirement":
        suggestions.append("- Look at electives or GE courses outside your major")

    suggestion_text = "\n".join(suggestions) if suggestions else "- Try broadening your search criteria"

    return (
        "I couldn't find courses that match all your criteria for this term. "
        "Here are some things you could try:\n"
        f"{suggestion_text}\n\n"
        "Want me to search again with looser filters?"
    )
